

SELECT DISTINCT 'ID'=T.ID,'NAME'=T.NAME,'FIRSTDAY'=T.FIRSTDAY,'LASTDAY'=T.LASTDAY ,'YEARID'=T.YEARID ,'ABBREVIATION'=T.ABBREVIATION ,'NOOFDAYS'=T.NOOFDAYS,'SCHOOLID'=T.SCHOOLID,'YEARLYCREDITHRS'=T.YEARLYCREDITHRS,'TERMSINYEAR'=T.TERMSINYEAR,'PORTION'=T.PORTION ,'IMPORTMAP'=ISnull(T.IMPORTMAP,''),'AUTOBUILDBIN'=T.AUTOBUILDBIN ,'ISYEARREC'=T.ISYEARREC,'PERIODS_PER_DAY'=T.PERIODS_PER_DAY,'DAYS_PER_CYCLE'=T.DAYS_PER_CYCLE ,'ATTENDANCE_CALCULATION_CODE'=T.ATTENDANCE_CALCULATION_CODE,'STERMS'=T.STERMS                                          ,'TERMINFO_GUID'=ISNULL(T.TERMINFO_GUID,'')                 
FROM       PowerSchool.DBO.TERMS   T
INNER JOIN PowerSchool.DBO.SCHOOLS S ON T.SCHOOLID=S.SCHOOL_NUMBER
		AND S.SORTORDER BETWEEN 1 AND 33
WHERE 1=1
	AND T.YEARID in (SELECT DISTINCT yearid
	FROM PowerSchool.dbo.Terms
	WHERE isyearrec=1
		AND GETDATE() BETWEEN firstday AND lastday)
ORDER BY T.SCHOOLID
