


SELECT DISTINCT 
'ID'=T.ID,'LASTFIRST'=T.LASTFIRST,'FIRST_NAME'=T.FIRST_NAME,'MIDDLE_NAME'=ISNULL(T.MIDDLE_NAME,''),'LAST_NAME'=T.LAST_NAME,'SCHOOLID'=T.SCHOOLID,'STATUS'=T.STATUS,'TITLE'=T.TITLE,'HOMEROOM'=ISNULL(T.HOMEROOM,''),'EMAIL_ADDR'=T.EMAIL_ADDR,'LOGINID'=T.TEACHERLOGINID,'TEACHERNUMBER'=T.TEACHERNUMBER,'Staffstatus'=T.STAFFSTATUS,'TeacherLoginID'=T.TEACHERLOGINID,'StateID'=ISNULL(T.SIF_STATEPRID,'')

FROM PowerSchool.DBO.TEACHERS T
INNER JOIN PowerSchool.DBO.SCHOOLS S ON T.SCHOOLID=S.SCHOOL_NUMBER
		AND S.SORTORDER BETWEEN 1 AND 33
		
WHERE 1=1
AND T.STATUS=1
AND T.TITLE LIKE ('Teacher%')
and t.SCHED_SCHEDULED=1

Order by t.LASTFIRST